library(pointblank)

agent <-
  create_agent(
    tbl = ~df,
    actions = action_levels(
      warn_at = 0.05,
      stop_at = 0.10
    ),
    tbl_name = "ecri",
    label = "Validation plan generated by `draft_validation()`."
  ) %>%
  # Expect that column `StuID` is of type: numeric
  col_is_numeric(
    columns = vars(StuID)
  ) %>%
  # Expect that values in `StuID` should be between `1` and `6136`
  col_vals_between(
    columns = vars(StuID),
    left = 1,
    right = 6136
  ) %>%
  # Expect that column `Tier` is of type: numeric
  col_is_numeric(
    columns = vars(Tier)
  ) %>%
  # Expect that values in `Tier` should be between `2` and `2`
  col_vals_between(
    columns = vars(Tier),
    left = 2,
    right = 2
  ) %>%
  # Expect that column `SchlID` is of type: numeric
  col_is_numeric(
    columns = vars(SchlID)
  ) %>%
  # Expect that values in `SchlID` should be between `1` and `45`
  col_vals_between(
    columns = vars(SchlID),
    left = 1,
    right = 45
  ) %>%
  # Expect that column `TeachID` is of type: numeric
  col_is_numeric(
    columns = vars(TeachID)
  ) %>%
  # Expect that values in `TeachID` should be between `3` and `231`
  col_vals_between(
    columns = vars(TeachID),
    left = 3,
    right = 231
  ) %>%
  # Expect that column `Tx` is of type: numeric
  col_is_numeric(
    columns = vars(Tx)
  ) %>%
  # Expect that values in `Tx` should be between `0` and `1`
  col_vals_between(
    columns = vars(Tx),
    left = 0,
    right = 1
  ) %>%
  # Expect that column `Cohort` is of type: numeric
  col_is_numeric(
    columns = vars(Cohort)
  ) %>%
  # Expect that values in `Cohort` should be between `1` and `1`
  col_vals_between(
    columns = vars(Cohort),
    left = 1,
    right = 1
  ) %>%
  # Expect that column `Keep` is of type: numeric
  col_is_numeric(
    columns = vars(Keep)
  ) %>%
  # Expect that values in `Keep` should be between `1` and `1`
  col_vals_between(
    columns = vars(Keep),
    left = 1,
    right = 1
  ) %>%
  # Expect that column `Time` is of type: numeric
  col_is_numeric(
    columns = vars(Time)
  ) %>%
  # Expect that values in `Time` should be between `1` and `3`
  col_vals_between(
    columns = vars(Time),
    left = 1,
    right = 3
  ) %>%
  # Expect that column `t` is of type: numeric
  col_is_numeric(
    columns = vars(t)
  ) %>%
  # Expect that values in `t` should be between `0` and `2`
  col_vals_between(
    columns = vars(t),
    left = 0,
    right = 2
  ) %>%
  # Expect that column `NWFcls` is of type: numeric
  col_is_numeric(
    columns = vars(NWFcls)
  ) %>%
  # Expect that values in `NWFcls` should be between `4` and `221`
  col_vals_between(
    columns = vars(NWFcls),
    left = 4,
    right = 221,
    na_pass = TRUE
  ) %>%
  # Expect that column `NWFwrc` is of type: numeric
  col_is_numeric(
    columns = vars(NWFwrc)
  ) %>%
  # Expect that values in `NWFwrc` should be between `0` and `78`
  col_vals_between(
    columns = vars(NWFwrc),
    left = 0,
    right = 78,
    na_pass = TRUE
  ) %>%
  # Expect that column `ORFwc` is of type: numeric
  col_is_numeric(
    columns = vars(ORFwc)
  ) %>%
  # Expect that values in `ORFwc` should be between `0` and `141`
  col_vals_between(
    columns = vars(ORFwc),
    left = 0,
    right = 141,
    na_pass = TRUE
  ) %>%
  # Expect that column `SAwrS` is of type: numeric
  col_is_numeric(
    columns = vars(SAwrS)
  ) %>%
  # Expect that values in `SAwrS` should be between `361` and `608`
  col_vals_between(
    columns = vars(SAwrS),
    left = 361,
    right = 608,
    na_pass = TRUE
  ) %>%
  # Expect that column `SAsrS` is of type: numeric
  col_is_numeric(
    columns = vars(SAsrS)
  ) %>%
  # Expect that values in `SAsrS` should be between `375` and `632`
  col_vals_between(
    columns = vars(SAsrS),
    left = 375,
    right = 632,
    na_pass = TRUE
  ) %>%
  # Expect that column `SAtoS` is of type: numeric
  col_is_numeric(
    columns = vars(SAtoS)
  ) %>%
  # Expect that values in `SAtoS` should be between `445` and `665`
  col_vals_between(
    columns = vars(SAtoS),
    left = 445,
    right = 665,
    na_pass = TRUE
  ) %>%
  # Expect that column `RMwidRS` is of type: numeric
  col_is_numeric(
    columns = vars(RMwidRS)
  ) %>%
  # Expect that values in `RMwidRS` should be between `0` and `72`
  col_vals_between(
    columns = vars(RMwidRS),
    left = 0,
    right = 72,
    na_pass = TRUE
  ) %>%
  # Expect that column `RMwdaRS` is of type: numeric
  col_is_numeric(
    columns = vars(RMwdaRS)
  ) %>%
  # Expect that values in `RMwdaRS` should be between `0` and `38`
  col_vals_between(
    columns = vars(RMwdaRS),
    left = 0,
    right = 38,
    na_pass = TRUE
  ) %>%
  # Expect entirely distinct rows across all columns
  rows_distinct() %>%
  # Expect that column schemas match
  col_schema_match(
    schema = col_schema(
      StuID = "numeric",
      Tier = "numeric",
      SchlID = "numeric",
      TeachID = "numeric",
      Tx = "numeric",
      Cohort = "numeric",
      Keep = "numeric",
      Time = "numeric",
      t = "numeric",
      NWFcls = "numeric",
      NWFwrc = "numeric",
      ORFwc = "numeric",
      SAwrS = "numeric",
      SAsrS = "numeric",
      SAtoS = "numeric",
      RMwidRS = "numeric",
      RMwdaRS = "numeric"
    )
  ) %>%
  interrogate()

agent
